version: "3"
services:
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - "./mariadb/config:/etc/mysql/conf.d"
    #   - "./mariadb/data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=r00tP@sSw0rd
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-e", "SELECT true AS health"]

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - "./postgres/config:/etc/postgresql"
    #   - "./postgres/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=r00tP@sSw0rd
    healthcheck:
      test: ["CMD", "pg_isready"]

  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    # volumes:
    #   - "./sqlserver/config:/opt/mssql/lib/mssql-conf"
    #   - "./sqlserver/data:/var/opt/mssql"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=r00tP@sSw0rd
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "r00tP@sSw0rd", "-Q", "SELECT CAST(1 AS BIT) AS health"]

  mongo:
    image: mongo:4.2.6-bionic
    ports:
      - "27017:27017"
    # volumes:
    #   - "./mongo/config:/etc/mongo"
    #   - "./mongo/data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=r00tP@sSw0rd
    healthcheck:
      test: ["CMD", "mongo", "--eval", "quit()"]
